matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.6"
      
      install:
        - pip install --upgrade pip
        - pip install -U -r python/requirements.txt
      
      script:
        - cd python && python setup.py develop test
    - language: R
      sudo: false
      cache: packages
      # R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
