dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install --upgrade pip
  - pip install -U -r python/requirements.txt

script:
  - cd python && python setup.py develop test
  - python setup.py clean
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.22.1/cmdstan-2.22.1.tar.gz -O /tmp/cmdstan.tar.gz && tar -xvf /tmp/cmdstan.tar.gz -C /tmp
  - make -C /tmp/cmdstan-2.22.1/ build
  - CMDSTAN=/tmp/cmdstan-2.22.1 STAN_BACKEND=CMDSTANPY python setup.py develop test
