language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -U -r python/requirements.txt
  - pip install -U -r python/fbprophet-plot/requirements.txt

script:
  - cd python && python setup.py develop test
  - cd python && python setup-plot.py develop
